name: Masar TickLive Runner

on:
  schedule:
    - cron: "* * * * *"   
  workflow_dispatch:       

jobs:
  call_tick_live:
    runs-on: ubuntu-latest

    steps:
      - name: Call tick_live endpoint
        run: |
          curl -X POST https://masar-sim.onrender.com/tick_live
